#ifndef MORSE_CONTROL_H
#define MORSE_CONTROL_H

#include <stdint.h>
typedef enum {
  ACTION_NONE = 0, // no action / end of sequence
  ACTION_SHORT,    // dot, short pulse
  ACTION_LONG,     // dash, long pulse
  ACTION_PAUSE     // pause between letters
} MorseAction;

#define MAX_MORSE_LEN 5

static const MorseAction MORSE_SEQ[26][MAX_MORSE_LEN] = {
    {ACTION_SHORT, ACTION_LONG, ACTION_NONE, ACTION_NONE, ACTION_NONE}, // A: .-
    {ACTION_LONG, ACTION_SHORT, ACTION_SHORT, ACTION_SHORT,
     ACTION_NONE}, // B: -...
    {ACTION_LONG, ACTION_SHORT, ACTION_LONG, ACTION_SHORT,
     ACTION_NONE}, // C: -.-.
    {ACTION_LONG, ACTION_SHORT, ACTION_SHORT, ACTION_NONE,
     ACTION_NONE}, // D: -..
    {ACTION_SHORT, ACTION_NONE, ACTION_NONE, ACTION_NONE, ACTION_NONE}, // E: .
    {ACTION_SHORT, ACTION_SHORT, ACTION_LONG, ACTION_SHORT,
     ACTION_NONE}, // F: ..-.
    {ACTION_LONG, ACTION_LONG, ACTION_SHORT, ACTION_NONE,
     ACTION_NONE}, // G: --.
    {ACTION_SHORT, ACTION_SHORT, ACTION_SHORT, ACTION_SHORT,
     ACTION_NONE}, // H: ....
    {ACTION_SHORT, ACTION_SHORT, ACTION_NONE, ACTION_NONE,
     ACTION_NONE}, // I: ..
    {ACTION_SHORT, ACTION_LONG, ACTION_LONG, ACTION_LONG,
     ACTION_NONE}, // J: .---
    {ACTION_LONG, ACTION_SHORT, ACTION_LONG, ACTION_NONE,
     ACTION_NONE}, // K: -.-
    {ACTION_SHORT, ACTION_LONG, ACTION_SHORT, ACTION_SHORT,
     ACTION_NONE}, // L: .-..
    {ACTION_LONG, ACTION_LONG, ACTION_NONE, ACTION_NONE, ACTION_NONE},  // M: --
    {ACTION_LONG, ACTION_SHORT, ACTION_NONE, ACTION_NONE, ACTION_NONE}, // N: -.
    {ACTION_LONG, ACTION_LONG, ACTION_LONG, ACTION_NONE, ACTION_NONE}, // O: ---
    {ACTION_SHORT, ACTION_LONG, ACTION_LONG, ACTION_SHORT,
     ACTION_NONE}, // P: .--.
    {ACTION_LONG, ACTION_LONG, ACTION_SHORT, ACTION_LONG,
     ACTION_NONE}, // Q: --.-
    {ACTION_SHORT, ACTION_LONG, ACTION_SHORT, ACTION_NONE,
     ACTION_NONE}, // R: .-.
    {ACTION_SHORT, ACTION_SHORT, ACTION_SHORT, ACTION_NONE,
     ACTION_NONE},                                                     // S: ...
    {ACTION_LONG, ACTION_NONE, ACTION_NONE, ACTION_NONE, ACTION_NONE}, // T: -
    {ACTION_SHORT, ACTION_SHORT, ACTION_LONG, ACTION_NONE,
     ACTION_NONE}, // U: ..-
    {ACTION_SHORT, ACTION_SHORT, ACTION_SHORT, ACTION_LONG,
     ACTION_NONE}, // V: ...-
    {ACTION_SHORT, ACTION_LONG, ACTION_LONG, ACTION_NONE,
     ACTION_NONE}, // W: .--
    {ACTION_LONG, ACTION_SHORT, ACTION_SHORT, ACTION_LONG,
     ACTION_NONE}, // X: -..-
    {ACTION_LONG, ACTION_SHORT, ACTION_LONG, ACTION_LONG,
     ACTION_NONE}, // Y: -.--
    {ACTION_LONG, ACTION_LONG, ACTION_SHORT, ACTION_SHORT,
     ACTION_NONE} // Z: --..
};

void play_morse_text(const char *text, void (*beep_func)(int duration_ms));
void set_morse_speed(int speed_ms);
int get_morse_speed(void);

#endif
